token: ""
path: ["/osnova/-1.d/1-f/","/osnova/-1.d/2-f/"]
minerName:
apiKey: 950554c1-2786-4caa-9c8b-dc8461019dd5
cachePath: ""
deviceId: ""
extraParams: {}
log:
  lv: info
  path: ./log/
  name: miner.log
url:
  info: ""
  submit: ""
  line: ""
  ws: ""
  proxy: ""
scanPath: true
scanMinute: 10
debug: ""
language: en
line: jp
multithreadingLoad: true
