token: ""
path: ["/osnova/-1.d/1-f/","/osnova/-1.d/2-f/"]
minerName:
apiKey: chiaog00-e7f4-4ded-8bcc-bed46cb88321
cachePath: ""
deviceId: ""
extraParams: {}
log:
  lv: info
  path: ./log/
  name: miner.log
url:
  info: ""
  submit: ""
  line: ""
  ws: ""
  proxy: ""
scanPath: true
scanMinute: 10
debug: ""
language: en
line: jp
multithreadingLoad: true
